[pytest]

# 核心运行参数
minversion = 8.0.0
# -v: 详细输出; -s: 允许控制台打印; -p no:warnings: 屏蔽第三方库警告信息
addopts = -vs -p no:warnings --alluredir=reports/allure_results --clean-alluredir


# 异步引擎配置
# 开启 auto 模式后，所有的 async def test_xxx() 都会自动被当做异步用例执行
# 无需 @pytest.mark.asyncio 装饰器
asyncio_mode = auto


# 收集规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*


# 控制台与日志格式
console_output_style = progress
xfail_strict = True
empty_parameter_set_mark = xfail

# 即使我们使用了 utils.logger (loguru)，这里配置 Pytest 原生日志格式也能兜底捕获异常
log_cli = False
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S


# 自定义标签树 (Custom Markers)
# 规范化业务标签，防止 QA 拼写错误导致跑漏用例
markers =
    p0: 核心主干流程 (Blocker/Critical)，发版前必跑
    p1: 重要功能验证 (Normal)，日常回归跑
    p2: 边缘异常场景 (Minor/Trivial)
    wms: 仓储管理系统 (Warehouse Management System) 专属测试
    rms: 机器人调度系统 (Robot Management System) 专属测试
    pda: 移动手持终端交互 专属测试