import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

from config.settings import settings
from utils.logger import log

__all__ = ['email_notifier']


class EmailNotifier:
    """自动化测试邮件推送引擎"""

    def __init__(self):
        self.conf = settings.email

    def _generate_html_body(self, summary: dict[str, Any]) -> str:
        """生成现代化的精美 HTML 邮件正文"""

        color = '#28a745' if summary['result'] == 'Success' else '#dc3545'
        run_env = summary.get('run_env', '-')
        runner_host = summary.get('runner_host', '-')
        target_hosts = summary.get('target_hosts') or {}
        target_line = '、'.join(f'{k.removeprefix("Target.")}={v}' for k, v in target_hosts.items()) or '-'
        report_url = summary.get('allure_report_url') or '#'

        html_template = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                .link-btn {{ display: inline-block; padding: 10px 20px; margin-top: 15px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px; font-weight: bold; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h2>📊 {settings.report.title}</h2>
                </div>
                <div class="content">
                    <p>您好，以下是本次 API 自动化测试的执行摘要：</p>

                    <p><strong>运行环境：</strong> {run_env} &nbsp;|&nbsp; <strong>执行机 IP：</strong> {runner_host}</p>
                    <p><strong>被测服务：</strong> {target_line}</p>
                    <p><strong>执行任务：</strong> {settings.report.tester_name}</p>

                    <table class="summary-table">
                        <tr><th>运行结果</th><td colspan="3" style="color:{color}; font-weight:bold;">{summary['result']}</td></tr>
                        <tr><th>开始时间</th><td colspan="3">{summary['started_time']}</td></tr>
                        <tr><th>运行耗时</th><td colspan="3">{summary['elapsed_time']}</td></tr>
                        <tr>
                            <th>总用例数</th><th>通过 (Pass)</th><th>失败 (Fail)</th><th>错误 (Error)</th>
                        </tr>
                        <tr>
                            <td>{summary['total']}</td>
                            <td class="pass">{summary['passed']}</td>
                            <td class="fail">{summary['failed']}</td>
                            <td class="fail">{summary['error']}</td>
                        </tr>
                    </table>

                    <div style="text-align: center;">
                        <a href="{report_url}" class="link-btn">👉 点击查看详细 Allure 报告</a>
                    </div>
                </div>
                <div class="footer">
                    This is an automated message generated by RMS API Test Framework.
                </div>
            </div>
        </body>
        </html>
        """
        return html_template

    def send_report(self, summary_data: dict[str, Any], attach_file: Path | None = None) -> None:
        """
        发送测试结果摘要邮件

        :param summary_data: 从 conftest.py 收集的汇总数据
        :param attach_file: 需要作为附件上传的文件路径 (如 summary.yaml)
        """
        if not self.conf.send:
            log.info('邮件推送开关未开启 (settings.email.send=False)，已跳过发送。')
            return

        log.info('📧 正在准备发送测试报告邮件...')

        try:
            msg = MIMEMultipart()
            msg['Subject'] = f"[{summary_data['result']}] {settings.report.title}"
            msg['From'] = self.conf.user

            # 处理单发或群发
            receivers = self.conf.receiver if isinstance(self.conf.receiver, list) else [self.conf.receiver]
            msg['To'] = ','.join(receivers)

            # 1. 附加美化的 HTML 正文
            html_body = self._generate_html_body(summary_data)
            msg.attach(MIMEText(html_body, 'html', 'utf-8'))

            # 2. 附加文件 (如果有)
            if attach_file and attach_file.exists():
                with open(attach_file, 'rb') as f:
                    attachment = MIMEApplication(f.read())
                    attachment.add_header('Content-Disposition', 'attachment', filename=attach_file.name)
                    msg.attach(attachment)

            # 3. 连接 SMTP 服务器并发送
            if self.conf.ssl:
                smtp = smtplib.SMTP_SSL(self.conf.host, self.conf.port)
            else:
                smtp = smtplib.SMTP(self.conf.host, self.conf.port)

            smtp.login(self.conf.user, self.conf.password)
            smtp.sendmail(self.conf.user, receivers, msg.as_string())
            smtp.quit()

            log.info(f'✅ 测试报告邮件发送成功！收件人: {receivers}')

        except Exception as e:
            log.error(f"❌ 邮件发送失败: {e}")


email_notifier = EmailNotifier()